name: mariadb test build for Android

# Controls when the workflow will run
on:
 workflow_dispatch:
  inputs:
      tagname:
        description: 'tagname'
        required: true
        default: '8.0.x'
      prefix:
        description: 'your package name'
        required: true
        default: 'ph.STICKnoLOGIC.com.laramobi'
      createRelease:
        description: 'If "yes", create the release.'
        required: true
        default: 'yes'
      version:
        description: 'version'
        required: true
        default : 'v1Beta'

jobs:
   building-mdb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup Environment for Cross-compiling for Android ARMv8 (aarch64)
        run: |
          source ./installer
          setup_mdb_env
          echo "$(pwd)/aarch64-linux-musl/bin" >> $GITHUB_PATH
          
      - name: install
        run: |
          source ./installer && cd $BUILD_DIR && build_mdb
