# This is a basic workflow to help you get started with Actions

name: mysql test build for Android

# Controls when the workflow will run
on:
 workflow_dispatch:
  inputs:
      tagname:
        description: 'tagname'
        required: true
        default: '8.0.x'
      prefix:
        description: 'your package name'
        required: true
        default: 'ph.STICKnoLOGIC.com.laramobi'
      createRelease:
        description: 'If "yes", create the release.'
        required: true
        default: 'yes'
      version:
        description: 'version'
        required: true
        default : 'v1Beta'

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - name: init directories
        run: mkdir -p aarch64-linux-musl
      - name: fetch aarch64-linux-musl from github release
        working-directory: aarch64-linux-musl
        run: wget -q -O "aarch64-linux-musl.tar.xz" "https://github.com/STICKnoLOGIC/musl-cross-make/releases/latest/download/aarch64-linux-musl.tar.xz"
        
      - name: unzip aarch64-linux-musl and append path
        working-directory: aarch64-linux-musl
        run: |
          tar Jxfv aarch64-linux-musl.tar.xz > /dev/null
          echo "$(pwd)/bin" >> $GITHUB_PATH
    
      - uses: actions/checkout@v3
      
      - name: update system
        run: |
         sudo apt update &> /dev/null 
         sudo apt-get install build-essential install-info libncurses5-dev bison groff dh-autoreconf libcurl4-gnutls-dev libexpat1-dev \
         gettext libz-dev libssl-dev
       
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir $HOME/output
          echo ""
          echo "This may take some time, please sit back and take a coffee."
          echo ""
          mkdir -p output
          git clone --depth 1 --shallow-submodules https://github.com/git/git.git
          cd git
          export NO_OPENSSL=1
          export NO_CURL=1
          export CFLAGS="${CFLAGS} -static"
          make configure
          ./configure --prefix=$HOME/output
          make -j $(nproc)
          make install
          #chmod -R a+r /output
    -uses: actions/upload-artifact@v3
      with:
       name: my-artifact
       path: $HOME/output
