# This is a basic workflow to help you get started with Actions

name: mysql test build for Android

# Controls when the workflow will run
on:
 workflow_dispatch:
  inputs:
      tagname:
        description: 'tagname'
        required: true
        default: '8.0.x'
      prefix:
        description: 'your package name'
        required: true
        default: 'ph.STICKnoLOGIC.com.laramobi'
      createRelease:
        description: 'If "yes", create the release.'
        required: true
        default: 'yes'
      version:
        description: 'version'
        required: true
        default : 'v1Beta'

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: update system
        run: |
         sudo apt update &> /dev/null 
         sudo apt-get install build-essential libncurses5-dev bison groff
       
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          curl -o ./mysql.tar.gz http://cdn.mysql.com/archives/mysql-5.0/mysql-5.0.51a.tar.gz
          tar -zxvf mysql.tar.gz
          cd ./mysql
          make distclean
          ./configure --enable-assembler --disable-community-features --without-debug --with-mysqld-ldflags=-all-static --prefix=/data/data/com.solusiprogram.mysql/app_HOME/lib/mysql --without-query-cache  --without-geometry  --without-extra-tools  --disable-shared --disable-profiling --disable-grant-options --disable-largefile --without-uca --without-docs --without-man --without-ndb-debug --without-bench
          make
          make install
          
