# This is a basic workflow to help you get started with Actions

name: mysql test build for Android

# Controls when the workflow will run
on:
 workflow_dispatch:
  inputs:
      tagname:
        description: 'tagname'
        required: true
        default: '8.0.x'
      prefix:
        description: 'your package name'
        required: true
        default: 'ph.STICKnoLOGIC.com.laramobi'
      createRelease:
        description: 'If "yes", create the release.'
        required: true
        default: 'yes'
      version:
        description: 'version'
        required: true
        default : 'v1Beta'

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: update system
        run: |
         sudo apt update &> /dev/null 
         sudo apt-get install build-essential libncurses5-dev bison groff
       
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          cd $HOME
          mkdir output && cd output
          mkdir mysql && cd
          GIT_VERSION=git-2.9.5
          GIT_PATH=/usr/local/git/bin
          DOWNLOAD_PATH=https://www.kernel.org/pub/software/scm/git/$GIT_VERSION.tar.gz
          apt install -y wget autoconf make gcc curl-devel expat-devel gettext-devel openssl-devel zlib-devel perl-ExtUtils-CBuilder perl-ExtUtils-MakeMaker libxslt asciidoc xmlto
          wget $DOWNLOAD_PATH
          tar xzvf $GIT_VERSION.tar.gz
          cd $GIT_VERSION
          make prefix=/usr/local/git all
          make prefix=/usr/local/git install
          source contrib/completion/git-completion.bash

#-------------------------------------------------------------------------------
# 安装依赖的软件
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# 下载git
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# 编译
#-------------------------------------------------------------------------------
