# This is a basic workflow to help you get started with Actions

name: mysql test build for Android

# Controls when the workflow will run
on:
 workflow_dispatch:
  inputs:
      tagname:
        description: 'tagname'
        required: true
        default: '8.0.x'
      prefix:
        description: 'your package name'
        required: true
        default: 'ph.STICKnoLOGIC.com.laramobi'
      createRelease:
        description: 'If "yes", create the release.'
        required: true
        default: 'yes'
      version:
        description: 'version'
        required: true
        default : 'v1Beta'

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: update system
        run: |
         sudo apt update &> /dev/null 
         sudo apt-get install build-essential libncurses5-dev bison groff
       
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          cd $HOME
          mkdir output && cd output
          mkdir mysql && cd
          wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.23.tar.gz
          tar -zxvf mysql-8.0.23.tar.gz
          cd ./mysql-8.0.23
          
          mkdir bld
          cd bld
          cmake .. -DMAX_INDEXES=255 -DDOWNLOAD_BOOST=0 -DWITH_BOOST=/tmp/
