on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'tagname'
        required: true
        default: '8.0.x'
      commithash:
        description: 'commit hash'
        required: true
        default: 'none'
      createRelease:
        description: 'If "yes", create the release.'
        required: true
        default: 'yes'
      version:
        description: 'version'
        required: true
        default : 'v1Beta'

name: Release Binaries for Project:LARA

jobs:
  build-php:
    name: Building cross compiler for android-aarch64
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
          include:
            - option: ""
              name: "-v_8.0.x"
              branch: "php/8.0"
              upload-php-ini: "no"
              musl-cross-make-repo: "STICKnoLOGIC/musl-cross-make"
            - option: "-g"
              name: "-v_8.0.x-og"
              branch: "php/8.0"
              upload-php-ini: "no"
              musl-cross-make-repo: "STICKnoLOGIC/musl-cross-make"
            - option: "-P 4"
              name: ""
              branch: "php/8.1"
              upload-php-ini: "no"
              musl-cross-make-repo: "STICKnoLOGIC/musl-cross-make"
            - option: "-g -P 4"
              name: "-v_8.1.x"
              branch: "php/8.1"
              upload-php-ini: "no"
              musl-cross-make-repo: "ScerIO/musl-cross-make"
            - option: "-g -P 5"
              name: "-og"
              branch: "php/8.1"
              upload-php-ini: ""
              musl-cross-make-repo: "STICKnoLOGIC/musl-cross-make"
            - option: "-g -P 4"
              name: "-v_8.1.x"
              branch: "php/8.1"
              upload-php-ini: "-v_8.1.x"
              musl-cross-make-repo: "STICKnoLOGIC/musl-cross-make"
            - option: "-g -P 5"
              name: "-v_8.2.x"
              branch: "php/8.2"
              upload-php-ini: "-v_8.2.x"
              musl-cross-make-repo: "STICKnoLOGIC/musl-cross-make"
            # Please note that if editing the matrix, the release workflow must also be edited.
    steps:
      - name: init directories
        run: mkdir -p aarch64-linux-musl
      - name: fetch aarch64-linux-musl from github release
        working-directory: aarch64-linux-musl
        run: wget -q -O "aarch64-linux-musl.tar.xz" "https://github.com/${{ matrix.musl-cross-make-repo }}/releases/latest/download/aarch64-linux-musl.tar.xz"
        
      - name: unzip aarch64-linux-musl and append path
        working-directory: aarch64-linux-musl
        run: |
          tar Jxfv aarch64-linux-musl.tar.xz > /dev/null
          echo "$(pwd)/bin" >> $GITHUB_PATH
          
      - uses: actions/checkout@v2
        with:
         repository: STICKnoLOGIC/php-build-scripts
         path: php-build-scripts
         ref: ${{ matrix.branch }}
         
      - name: Checkout php-build-scripts commit
        if: ${{ github.event.inputs.commithash != 'none' }}
        working-directory: php-build-scripts
        run: git checkout "${{ github.event.inputs.commithash }}"
        
      - name: install module
        run: |
          sudo apt update &> /dev/null
          sudo apt install -y re2c libtool libtool-bin zlib1g-dev libcurl4-openssl-dev libxml2-dev libyaml-dev libgmp-dev libzip-dev libssl-dev &> /dev/null
          
      - name: making aarch64 php
        working-directory: php-build-scripts
        run: ./compile.sh -t android-aarch64 -x -j2 -f ${{ matrix.option }}
        
      - name: copy php
        run: cp ./php-build-scripts/bin/php7/bin/php "php${{ matrix.name }}"
        
      - uses: actions/upload-artifact@v1
        with:
          name: "php${{ matrix.name }}"
          path: "./php${{ matrix.name }}"
          
      - name: copy php.ini
        if: ${{ matrix.upload-php-ini != 'no'}}
        run: cp ./php-build-scripts/bin/php7/bin/php.ini ./php${{ matrix.upload-php-ini }}.ini
        
      - uses: actions/upload-artifact@v1
        if: ${{ matrix.upload-php-ini != 'no'}}
        with:
          name: php${{ matrix.upload-php-ini }}.ini
          path: "./php${{ matrix.upload-php-ini }}.ini"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Linux
          path: |
            ./php-build-scripts/install.log
            ./php-build-scripts/compile.sh
          if-no-files-found: error

  commit-php:
    name: release
    needs: build-php
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.createRelease == 'yes'}}
    steps:
      - name: Download a Build Artifact(php)
        uses: actions/download-artifact@v2
        with:
          name: php

      - name: Download a Build Artifact(php-og)
        uses: actions/download-artifact@v2
        with:
          name: php-og
          
      - name: Download a Build Artifact(php-v_8.0.x)
        uses: actions/download-artifact@v2
        with:
          name: php-v_8.0.x

      - name: Download a Build Artifact(php-v_8.0.x-og)
        uses: actions/download-artifact@v2
        with:
          name: php-v_8.0.x-og

      - name: Download a Build Artifact(php-v_8.1.x)
        uses: actions/download-artifact@v2
        with:
          name: php-v_8.1.x

      - name: Download a Build Artifact(php-v_8.2.x)
        uses: actions/download-artifact@v2
        with:
          name: php-v_8.2.x

      - name: Download a Build Artifact(php.ini)
        uses: actions/download-artifact@v2
        with:
          name: php.ini
      - name: Download a Build Artifact(php-v_8.1.x.ini)
        uses: actions/download-artifact@v2
        with:
          name: php-v_8.1.x.ini
      - name: Download a Build Artifact(php-v_8.2.x.ini)
        uses: actions/download-artifact@v2
        with:
          name: php-v_8.2.x.ini


      - name: file compressions
        run: |
          zip -9 zip-php php
          zip -9 zip-php-og.zip php-og
          zip -9 zip-php-v_8.0.x.zip php-v_8.0.x
          zip -9 zip-php-v_8.0.x-og.zip php-v_8.0.x-og
          zip -9 zip-php-v_8.1.x.zip php-v_8.1.x
          zip -9 zip-php-v_8.2.x.zip php-v_8.2.x
          
      - name: create checksums.sha256
        run: |
          sha256sum "php-v_8.0.x" "php-v_8.0.x-og" "php" "php-og" "php-v_8.1.x" "php-v_8.2.x" "zip-php.zip" "zip-php-og.zip" "zip-php-v_8.1.x.zip" "zip-php-v_8.2.x.zip" "php.ini" "php-v_8.1.x.ini" "php-v_8.2.x.ini" > checksums.sha256
          cat checksums.sha256
          
      - uses: actions/upload-artifact@v1
        with:
          name: "checksums.sha256"
          path: "./checksums.sha256"
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          files: |
            php
            php-og
            php-v_8.0.x
            php-v_8.0.x-og
            php-v_8.1.x
            php-v_8.2.x
            zip-php.zip
            zip-php-og.zip
            zip-php-v_8.0.x.zip
            zip-php-v_8.0.x-og.zip
            zip-php-v_8.1.x.zip
            zip-php-v_8.2.x.zip
            php.ini
            php-v_8.1.x.ini
            php-v_8.2.x.ini
            checksums.sha256
          body: "The php version for this release is ${{ github.event.inputs.tagname }} .

The download is available from the Assets dropdown.

#### Notes

This binary does not support jit.

This binary is for ARMv8 (aarch64, 64bit).

It does not work on arm (32bit).

All binaries are not compatible with pmmp3 and are for pmmp4.

the php or php-og binaries are recommended.

The php version of php-v_8.1.x and php-v_8.2.x are use for laravel 9 and 10, though it is on experimental phase.

All binaries does not have pthreads...
"
